// тут описываются названия экшенов для Redux'a
export const UPDATE_LIST = 'UPDATE_LIST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const UPDATE_LOADING = 'UPDATE_LOADING';
export const UPDATE_COLOR = 'UPDATE_COLOR';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const UPDATE_FILTER_CATEGORY = 'UPDATE_FILTER_CATEGORY';
export const UPDATE_FILTER_BRAND = 'UPDATE_FILTER_BRAND';
export const UPDATE_FILTER_COLOR = 'UPDATE_FILTER_COLOR';
export const UPDATE_FILTER_PRICE = 'UPDATE_FILTER_PRICE';
